pipeline:
  build:
    image: node:8.1-alpine
    commands: npm install

  publicar:
    image: plugins/docker
    tags: latest
    repo: fdiazcobos/dronedemo
    secrets: [ docker_password, docker_username]
