pipeline:
  build:
    image: node:8.1-alpine
    commands:
      - npm install

  publish: 
    image: plugins/docker
    repo: fdiazcobos/dronedemo
    tags: latest
    secrets: [ docker_username, docker_password ]